move to function

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -14,20 +14,41 @@ jobs:
 
     - name: Pre-job-submission prep
       run: |
+        run_curl () {
+          curl_output=$( $1 )
+          curl_return_code=$?
+
+          if (( $curl_return_code != 0 )); then
+            echo "Error contacting to AutoIQ. Message: ${curl_output}"
+            exit 1
+          fi
+        }
+
         # Get a session token for this run
-        curl_return_code=0
-        curl_output=$( curl -X GET  --no-progress-meter \
+        curl_command=curl -X GET  --no-progress-meter \
                         "http://autoiq.extremenetworks.com/auth/getSessionTokenFromPA" \
                         -H "accept: application/json" \
-                        -H "authorization: PAT ${{ secrets.AUTOIQ_PAT }}" )
-        curl_return_code=$?
+                        -H "authorization: PAT ${{ secrets.AUTOIQ_PAT }}"
+        run_curl "$curl_command"
+        session_token=$( echo "$curl_command" | jq -r '.result.sessionToken' )
+        echo $curl_output
 
-        if (( $curl_return_code != 0 )); then
-          echo "Error getting session token. Message: ${curl_output}"
-          exit 1
-        else
-          session_token=$( echo "${curl_output}" |  jq -r '.result.sessionToken' )
-        fi
+
+        # curl_return_code=0
+        # curl_output=$( curl -X GET  --no-progress-meter \
+        #                 "http://autoiq.extremenetworks.com/auth/getSessionTokenFromPA" \
+        #                 -H "accept: application/json" \
+        #                 -H "authorization: PAT ${{ secrets.AUTOIQ_PAT }}" )
+        # curl_return_code=$?
+
+        # if (( $curl_return_code != 0 )); then
+        #   echo "Error getting session token. Message: ${curl_output}"
+        #   exit 1
+        # else
+        #   session_token=$( echo "${curl_output}" |  jq -r '.result.sessionToken' )
+        # fi
+
+
 
         # Get list of available testbeds for each harness
         # harnesses: econ_auto(pytest), xiq_auto(robot), tcl
