Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -51,39 +51,42 @@ jobs:
           session_token=$( echo "${curl_output}" |  jq -r '.result.sessionToken' )
         fi
 
-        ### Get list of available testbeds for each harness
-        # harnesses: pytest, robot, tcl
-        # 11111111-2222-2222-2222-111111111111 (pytest), 11111111-6666-6666-6666-111111111111 (robot), 11111111-5555-5555-5555-111111111111 (tcl)
-        curl_return_code=0
-        curl_output=$( curl -X GET --no-progress-meter \
-                                    "http://autoiq.extremenetworks.com/tbedmgr/jobmgr/cicdPlatforms/pytest" \
-                                    -H "accept: application/json" \
-                                    -H "authorization: Bearer ${session_token}" )
-        curl_return_code=$?
+# Commented on 4/28/22 by petersadej
+# This is not currently needed here because we are deafulting to the DT testbed. May be needed in the future
+#
+# ### Get list of available testbeds for each harness
+# # harnesses: pytest, robot, tcl
+# # 11111111-2222-2222-2222-111111111111 (pytest), 11111111-6666-6666-6666-111111111111 (robot), 11111111-5555-5555-5555-111111111111 (tcl)
+# curl_return_code=0
+# curl_output=$( curl -X GET --no-progress-meter \
+#                             "http://autoiq.extremenetworks.com/tbedmgr/jobmgr/cicdPlatforms/pytest" \
+#                             -H "accept: application/json" \
+#                             -H "authorization: Bearer ${session_token}" )
+# curl_return_code=$?
 
-        if (( $curl_return_code != 0 )); then
-          echo "Error getting session token. Message: ${curl_output}"
-          exit 1
-        else
-          available_testbeds_pytest=$( echo "${curl_output}" | jq '.result[]' )
-        fi
+# if (( $curl_return_code != 0 )); then
+#   echo "Error getting session token. Message: ${curl_output}"
+#   exit 1
+# else
+#   available_testbeds_pytest=$( echo "${curl_output}" | jq '.result[]' )
+# fi
 
-        curl_return_code=0
-        curl_output=$( curl -X GET --no-progress-meter \
-                                    "http://autoiq.extremenetworks.com/tbedmgr/jobmgr/cicdPlatforms/robot" \
-                                    -H "accept: application/json" \
-                                    -H "authorization: Bearer ${session_token}" )
-        curl_return_code=$?
+# curl_return_code=0
+# curl_output=$( curl -X GET --no-progress-meter \
+#                             "http://autoiq.extremenetworks.com/tbedmgr/jobmgr/cicdPlatforms/robot" \
+#                             -H "accept: application/json" \
+#                             -H "authorization: Bearer ${session_token}" )
+# curl_return_code=$?
 
-        if (( $curl_return_code != 0 )); then
-          echo "Error getting session token. Message: ${curl_output}"
-          exit 1
-        else
-          available_testbeds_robot=$( echo "${curl_output}" | jq '.result[]' )
-        fi
+# if (( $curl_return_code != 0 )); then
+#   echo "Error getting session token. Message: ${curl_output}"
+#   exit 1
+# else
+#   available_testbeds_robot=$( echo "${curl_output}" | jq '.result[]' )
+# fi
 
-        echo "pytest testbeds: $available_testbeds_pytest"
-        echo "robot testbeds: $available_testbeds_robot"
+# echo "pytest testbeds: $available_testbeds_pytest"
+# echo "robot testbeds: $available_testbeds_robot"
 
         echo "SESSION_TOKEN=${session_token}" >> $GITHUB_ENV
 
@@ -108,7 +111,7 @@ jobs:
                       {"context": "${{ github.event.repository.name }}/test-context"},
                       {"repo":"${{ github.repository }}"},
                       {"sha":"${{ github.sha }}"},
-                      {"state":""}
+                      {"state":"pending"}
                     ],
                     "jobPlatforms": [
                       {
@@ -133,8 +136,8 @@ jobs:
               }'
 
         # Format Test Lists
-        pytest_tests=$( echo "" | jq -ncR 'inputs | split(",")' )
-        robot_tests=$( echo "" | jq -ncR 'inputs | split(",")' )
+        pytest_tests=$( echo "Tests/Pytest/Demos/DefaultTemplateUI/TestCases,Tests/Pytest/Demos/VLAN/TestCases" | jq -ncR 'inputs | split(",")' )
+        robot_tests=$( echo "Tests/Robot/Demos/XiQ/TestCases" | jq -ncR 'inputs | split(",")' )
 
         pytest_harness_uuid="11111111-2222-2222-2222-111111111111"
         robot_harness_uuid="11111111-6666-6666-6666-111111111111"
@@ -143,31 +146,33 @@ jobs:
 
         # Generate robot JSON body
         CURL_BODY=$(jq --null-input \
-                  --arg tests "$robot_tests" \
+                  --argjson tests "$robot_tests" \
                   --arg harness_uuid "$robot_harness_uuid" \
                   "$job_template")
 
         echo "[*] Robot Job Submit JSON: $CURL_BODY"
 
-        curl -X POST --no-progress-meter \
-        "https://autoiq.extremenetworks.com/tbedmgr/jobmgr/createJob" \
-        -H "accept: application/json" \
-        -H "authorization: Bearer ${SESSION_TOKEN}" \
-        -d "${CURL_BODY}"
+        # curl -X POST --no-progress-meter \
+        # "https://autoiq.extremenetworks.com/tbedmgr/jobmgr/createJob" \
+        # -H "accept: application/json" \
+        # -H "Content-Type: application/json" \
+        # -H "authorization: Bearer ${SESSION_TOKEN}" \
+        # -d "${CURL_BODY}"
 
         # Generate pytest JSON body
         CURL_BODY=$(jq --null-input \
-                  --arg tests "$pytest_tests" \
+                  --argjson tests "$pytest_tests" \
                   --arg harness_uuid "$pytest_harness_uuid" \
                   "$job_template")
 
         echo "[*] Pytest Job Submit JSON: $CURL_BODY"
 
-        curl -X POST --no-progress-meter \
-        "https://autoiq.extremenetworks.com/tbedmgr/jobmgr/createJob" \
-        -H "accept: application/json" \
-        -H "authorization: Bearer ${SESSION_TOKEN}" \
-        -d "${CURL_BODY}"
+        # curl -X POST --no-progress-meter \
+        # "https://autoiq.extremenetworks.com/tbedmgr/jobmgr/createJob" \
+        # -H "accept: application/json" \
+        # -H "Content-Type: application/json" \
+        # -H "authorization: Bearer ${SESSION_TOKEN}" \
+        # -d "${CURL_BODY}"
 
 
     - name: Set job status output
