Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -14,43 +14,44 @@ jobs:
 
     - name: Pre-job-submission prep
       run: |
-        run_curl () {
-          echo $1
-          echo "$1"
-          curl_output=$( curl $1 )
-          curl_return_code=$?
+        # TODO: get this function working
+        ################################
+        # run_curl () {
+        #   echo $1
+        #   echo "$1"
+        #   curl_output=$( curl $1 )
+        #   curl_return_code=$?
 
-          if (( $curl_return_code != 0 )); then
-            echo "Error contacting to AutoIQ. Message: ${curl_output}"
-            exit 1
-          fi
-        }
+        #   if (( $curl_return_code != 0 )); then
+        #     echo "Error contacting to AutoIQ. Message: ${curl_output}"
+        #     exit 1
+        #   fi
+        # }
 
-        # Get a session token for this run
-        curl_command="-X GET --no-progress-meter \"http://autoiq.extremenetworks.com/auth/getSessionTokenFromPA\" -H \"accept: application/json\" -H \"authorization: PAT ${{ secrets.AUTOIQ_PAT }}\""
-        echo $curl_command
-        run_curl "$curl_command"
-        session_token=$( echo "$curl_command" | jq -r '.result.sessionToken' )
-        echo $curl_output
+        # # Get a session token for this run
+        # curl_command="-X GET --no-progress-meter \"http://autoiq.extremenetworks.com/auth/getSessionTokenFromPA\" -H \"accept: application/json\" -H \"authorization: PAT ${{ secrets.AUTOIQ_PAT }}\""
+        # echo $curl_command
+        # run_curl "$curl_command"
+        # session_token=$( echo "$curl_command" | jq -r '.result.sessionToken' )
+        # echo $curl_output
+        ################################
 
+        ### Get Session token
+        curl_return_code=0
+        curl_output=$( curl -X GET  --no-progress-meter \
+                        "http://autoiq.extremenetworks.com/auth/getSessionTokenFromPA" \
+                        -H "accept: application/json" \
+                        -H "authorization: PAT ${{ secrets.AUTOIQ_PAT }}" )
+        curl_return_code=$?
 
-        # curl_return_code=0
-        # curl_output=$( curl -X GET  --no-progress-meter \
-        #                 "http://autoiq.extremenetworks.com/auth/getSessionTokenFromPA" \
-        #                 -H "accept: application/json" \
-        #                 -H "authorization: PAT ${{ secrets.AUTOIQ_PAT }}" )
-        # curl_return_code=$?
+        if (( $curl_return_code != 0 )); then
+          echo "Error getting session token. Message: ${curl_output}"
+          exit 1
+        else
+          session_token=$( echo "${curl_output}" |  jq -r '.result.sessionToken' )
+        fi
 
-        # if (( $curl_return_code != 0 )); then
-        #   echo "Error getting session token. Message: ${curl_output}"
-        #   exit 1
-        # else
-        #   session_token=$( echo "${curl_output}" |  jq -r '.result.sessionToken' )
-        # fi
-
-
-
-        # Get list of available testbeds for each harness
+        ### Get list of available testbeds for each harness
         # harnesses: econ_auto(pytest), xiq_auto(robot), tcl
         # 11111111-2222-2222-2222-111111111111 (pytest), 11111111-6666-6666-6666-111111111111 (robot), 11111111-5555-5555-5555-111111111111 (tcl)
         curl_return_code=0
